<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>PayneLab</AssemblyName>
    <RootNamespace>PayneLab</RootNamespace>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CS8600;CS8601;CS8602;CS8603;CS8604</NoWarn>
    <OutputPath>..\..\BuildOutput\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>..\..\#1_Bonelab_Melon_References\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\#1_Bonelab_Melon_References\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BoneLib">
      <HintPath>..\..\#1_Bonelab_Melon_References\BoneLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\#1_Bonelab_Melon_References\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\#1_Bonelab_Melon_References\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\#1_Bonelab_Melon_References\UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\#1_Bonelab_Melon_References\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow">
      <HintPath>..\..\#1_Bonelab_Melon_References\Il2CppSLZ.Marrow.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow.VoidLogic.Core">
      <HintPath>..\..\#1_Bonelab_Melon_References\Il2CppSLZ.Marrow.VoidLogic.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow.VoidLogic.Engine">
      <HintPath>..\..\#1_Bonelab_Melon_References\Il2CppSLZ.Marrow.VoidLogic.Engine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\#1_Bonelab_Melon_References\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\#1_Bonelab_Melon_References\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyManifest" AfterTargets="Build">
    <Copy SourceFiles="manifest.json" DestinationFolder="$(OutputPath)" />
  </Target>
</Project>
